### ISSUE TITLE
Awesome name but dead project.

### ISSUE THREAD

**Issue by RyanScottLewis** [roja/system#1]
Would love to take over development of this gem! Lots of features could be added to this gem, such as [this](https://gist.github.com/4045482) and plenty more.

**Comment by roja** [comment]
I have added you as a collaborator if your happy to work on the gem. I will at some point pick it up again as my free time increases.

**Comment by RyanScottLewis** [comment]
Awesome! Thanks alot

**Comment by RyanScottLewis** [comment]
0.1.1 is ready to be published. Would you mind pulling in changes, `bundle install`, `rake gem`, and `gem push pkg/system-0.1.1.gem`?

Cheers!

**Comment by roja** [comment]
Fast work there :)

Will push it in the next 5 minutes or so.

R

**Comment by RyanScottLewis** [comment]
Thanks, I'm working on another gem which will rely on `System::CPU.count`.

Also, I have no life :smile:

**Comment by ioquatix** [comment]
Just bumping this thread, wondering if we can do a 1.0 release :D
