### ISSUE TITLE
Gem needs to be pushed.

### ISSUE THREAD

**Issue by RyanScottLewis** [roja/system#2]
It seems I cannot push it to RubyGems myself. 0.1.2 fixes a minor dependency issue.

Next version (0.1.3) will incorporate the code from kyledrake/running@bf590ea3fc into `System::Ruby`.

**Comment by roja** [comment]
Done. Thanks for the continued work.

**Comment by RyanScottLewis** [comment]
Of course! Love the OSS community.

I dunno why it won't let me push the gem but as long as it's getting out there, I dont really care.

Cheers,
Ryan
