### ISSUE TITLE
Speed improvements

### ISSUE THREAD

**Issue by ioquatix** [roja/system#3]
I made a Ruby based build system for C++. I was using Facter (a gem similar to system in some ways) for finding the number of concurrent compiler instances I can run. Ideally, we'd run about 1-2 instances per CPU core to compile everything as fast as possible and keep CPU saturated

I found that Facter was running `system_profiler` on Mac OS X to get lots of redundant information, which took about 0.5s just to get number of CPUs. It was causing a major slow down, especially if there was no work to do.

I switched to using this gem, and the speed was much better. I just wanted to tell you my use case and say thanks. Please keep this gem as fast as possible with as little overhead as possible. My use case probably isn't unique - just want to know the number of CPU cores - i.e. the maximum hardware concurrency.

**Comment by RyanScottLewis** [comment]
Thanks! We're actually just delegating all actual information gathering to either Java (on JRuby) or to system calls based on the current platform running the code. So, the creators of those programs are the actual ones to thank!

Cheers
